export enum ServerResponses {
  NO_LESSONS = 'NO_LESSONS',
  NO_TOPICS = 'NO_TOPICS',
  NO_LESSON_ID_PROVIDED = 'NO_LESSON_ID_PROVIDED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_INVITE_CODE = 'INVALID_INVITE_CODE'
}
